apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-arena-trakt
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    failureThreshold: 20
  readiness:
    path: /isready
    initialDelay: 5
    failureThreshold: 20
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 70
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 386Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  gcp:
    sqlInstances:
      - name: dp-arena-trakt
        type: POSTGRES_12
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: false
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: arena-data
            envVarPrefix: DB
        cascadingDelete: false
