ALTER TABLE sak
    ADD COLUMN IF NOT EXISTS opprettet TIMESTAMP,
    ADD COLUMN IF NOT EXISTS oppdatert TIMESTAMP;

ALTER TABLE vedtak
    ADD COLUMN IF NOT EXISTS opprettet TIMESTAMP,
    ADD COLUMN IF NOT EXISTS oppdatert TIMESTAMP;
