apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: dp-arena-trakt
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  parallelism: {{parallelism}}
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client