apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-arena-trakt
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  gcp:
    sqlInstances:
      - name: dp-arena-trakt
        type: POSTGRES_12
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: false
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: arena-data
            envVarPrefix: DB
        cascadingDelete: false