apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-arena-trakt
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    failureThreshold: 20
  readiness:
    path: /isready
    initialDelay: 5
    failureThreshold: 20
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    disableAutoScaling: true
  strategy:
    type: Recreate
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka.pool}}
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{kafka.consumer_group_id}}
  gcp:
    sqlInstances:
      - name: dp-arena-trakt-v4
        type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: false
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: arena-data
            envVarPrefix: DB
        cascadingDelete: false
