name: Build and deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/wrapper-validation@v4
      - uses: gradle/actions/setup-gradle@v4
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          dependency-graph: generate-and-submit
      - run: ./gradlew --configuration-cache build installDist

      - name: Build and push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdagpenger
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    name: Deploy to dev
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: app/.nais/nais.yaml,app/.nais/hpa.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: app/.nais/dev-vars.yaml
          PRINT_PAYLOAD: true

#  deploy-prod:
#    name: Deploy to Production
#    needs: [build]
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Fetch NAIS yaml
#        uses: actions/download-artifact@v4
#        with:
#          name: nais-yaml
#          path: nais
#
#      - uses: nais/deploy/actions/deploy@v2
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: nais/nais.yaml,nais/hpa.yaml
#          VARS: nais/prod-vars.yaml
#          PRINT_PAYLOAD: true