name: Batchlasting av data

on:
  workflow_dispatch:
    inputs:
      offsetStrategy:
        description: 'Hvilket offset skal vi begynne på?'
        required: true
        default: 'earliest'
        type: choice
        options:
          - earliest
          - latest

env:
  IMAGE: ghcr.io/${{ github.repository }}/dp-arena-trakt:${{ github.sha }}

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: jobb/.nais/nais.yaml
          VARS: jobb/.nais/dev-vars.yaml
          VAR: offset=${{ github.event.inputs.offsetStrategy }}
          PRINT_PAYLOAD: true

#  deploy-prod:
#    name: Deploy to Production
#    needs: [build]
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Fetch NAIS yaml
#        uses: actions/download-artifact@v1
#        with:
#          name: nais-yaml
#          path: nais
#
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: nais/nais.yaml
#          VARS: nais/prod-vars.yaml
#          PRINT_PAYLOAD: true